apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    app: second-pod
spec:
  containers:
   - name: container-pod-2
     image: gcr.io/k8s-minikube/storage-provisioner:v5
     ports:
      - containerPort: 80