apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-configmap
data:
  IP_SISTEMA: http://192.168.99.100:30001
  # if os os windows --> IP_SISTEMA: http://localhost:30001
  # if os os linux --> IP_SISTEMA: http://192.168.99.100:30001
  