apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    app: first-pod
spec:
  containers:
   - name: container-pod-1
     image: gcr.io/k8s-minikube/storage-provisioner:v5
     ports:
      - containerPort: 80